version: '3'

services:
  truckpad-api:
    build: .
    ports:
      - '5000:5000'
     
  mysqldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: truckpad_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: L1v2f3s4
    volumes:
      - ./sql-dump:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
